services:
  springapp:
    build: .
    ports:
      - ${SERVER_PORT}:8081
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
      - EXPIRATION_TIME=${EXPIRATION_TIME}
