# Imagen con Maven + JDK para desarrollo
FROM maven:3.9.6-eclipse-temurin-17

# Establece el directorio de trabajo
WORKDIR /app

# Copia solo los archivos necesarios para instalar dependencias primero (optimiza cache)
COPY .mvn .mvn
COPY mvnw pom.xml ./

# Descarga las dependencias (esto se cachea si no cambia el pom.xml)
RUN ./mvnw dependency:go-offline

# Copia el resto del código fuente
COPY . .

# Usa spring-boot:run en lugar de jar
CMD ["./mvnw", "spring-boot:run"]
