spring:
  profiles:
    active: local
  application:
    name: spring
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    cache: false
    check-template-location: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
  main:
    banner-mode: "off"

server:
  port: 8081
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: ${EXPIRATION_TIME}
  user:
    name:
    password: