spring:
  profiles:
    active: local
  application:
    name: spring
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
  main:
    banner-mode: "off"

server:
  port: 8081
