# Upstream para frontend Angular (sirve en el puerto 4200 en dev normalmente, pero en docker es el 3000)
upstream frontend {
    server frontend:4200;
}

# Upstream para backend Spring Boot (está en el puerto 8080 según tu docker-compose)
upstream backend {
    server backend:8081;
}

server {
    listen 80;

    # Rutas del frontend
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Rutas del backend (con prefijo /api como en tu Spring Boot)
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Rutas de WebSocket
    location /websocket/ {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
